apiVersion: v1
kind: Service
metadata:
  name: ollama-gpt-oss-20b
  namespace: gpt-oss
  labels:
    app: ollama-gpt-oss-20b
spec:
  selector:
    app: ollama-gpt-oss-20b
  ports:
    - name: http
      port: 11434
      targetPort: http
      protocol: TCP
