apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpt-oss

resources:
  - namespace.yaml
  - secret-hf-token.yaml
  - secret-quay-pull.yaml
  - deployment-clean.yaml
  - service.yaml
  - route.yaml
