apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"vllm-gpt-oss-120b","namespace":"gpt-oss"},"spec":{"ports":[{"name":"http","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"vllm-gpt-oss-120b"},"type":"ClusterIP"}}
  creationTimestamp: "2025-11-02T01:19:10Z"
  name: vllm-gpt-oss-120b
  namespace: gpt-oss
  resourceVersion: "89421"
  uid: 5eaabdd6-b2a1-4108-83fb-46c4e9d52e95
spec:
  clusterIP: 172.30.127.208
  clusterIPs:
  - 172.30.127.208
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: vllm-gpt-oss-120b
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
